Rasa process starting
Rasa process starting
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 178, in _do_read
    read = reader(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\_socket3.py", line 429, in recv_into
    return _socket.socket.recv_into(self._sock, *args)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 17
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 71, in get_json
    data = self._get_data_for_json(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\wrappers.py", line 50, in _get_data_for_json
    return self.get_data(cache=cache)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 514, in get_data
    rv = self.stream.read()
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 316, in read
    return self._do_read(length)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\pywsgi.py", line 195, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 15
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu\component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'action_joke'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
